name: qirha
description: "Qirha est une application mobile de vente en ligne révolutionnaire qui offre une expérience d'achat fluide et intuitive et permettant aux utilisateurs de parcourir une large gamme de produits, de passer des commandes en toute simplicité et de bénéficier d'une livraison rapide et sécurisée."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  heroicons: ^0.11.0
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  sticky_headers: ^0.3.0+2
  camera: ^0.11.2+1
  glass: ^2.0.0+2
  dio: ^5.3.3
  permission_handler: ^12.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  toastification: ^3.0.3
  extended_masked_text: ^3.0.1
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  dotted_border: ^3.1.0
  flutter_smart_dialog: ^4.9.6
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  fade_shimmer: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/AppIcon/app-white.png
    - assets/AppIcon/app.png
    - assets/placeholder.png
    - assets/cart.gif
    - assets/mtn.png
    - assets/airtel.jpg
    - assets/facebook.png
    - assets/google.png
    - assets/whatsapp.png
    - assets/bg.jpg
    - assets/money_hand.png
    - assets/mastercard.png
    - assets/visa.jpg
    - assets/security.png
    - assets/congo_rc.jpeg
    - assets/circle-loader.png
    - assets/need_login.svg
    - assets/pin-circle.png

    - assets/banner/banner-1.png
    - assets/banner/banner-3.png
    - assets/banner/banner-4.png
    - assets/banner/banner-5.png
    - assets/livraison.svg

    - assets/mode/beaute.png
    - assets/mode/chaussures.png
    - assets/mode/curvy.png
    - assets/mode/electronique.png
    - assets/mode/enfant.png
    - assets/mode/femme.png
    - assets/mode/homme.png
    - assets/mode/jeans.png
    - assets/mode/lingerie.png
    - assets/mode/maison.png
    - assets/mode/pulls.png
    - assets/mode/sac.png
    - assets/mode/accessoires.png
    - assets/mode/bas.png
    - assets/mode/bijoux.png
    - assets/mode/cuisine.png
    - assets/mode/maison_deco.png
    - assets/mode/robes.png
    - assets/mode/sports.png
    - assets/mode/sweat_shirts.png
    - assets/mode/textile.png
    - assets/mode/tops.png
    - assets/mode/vetement_exterieur.png
    - assets/mode/electromenager.png
    - assets/mode/bazard1.png
    - assets/mode/bazard2.png
    - assets/mode/bazard3.png
    - assets/mode/bazard4.png
    - assets/mode/bazard5.png
    - assets/mode/bazard6.png
    - assets/mode/new.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
